// <auto-generated />
using System;
using Altinn.Verification.Integrations.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Altinn.Verification.Integrations.Migrations
{
    [DbContext(typeof(VerificationDbContext))]
    [Migration("20260615143246_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Altinn.Verification.Core.AddressVerifications.Models.VerificationCode", b =>
                {
                    b.Property<int>("VerificationCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("verification_code_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VerificationCodeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_type");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempts");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationCodeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_code_hash");

                    b.HasKey("VerificationCodeId")
                        .HasName("verification_code_id_pkey");

                    b.HasIndex(new[] { "UserId", "Address", "AddressType" }, "ix_user_id_address_address_type")
                        .IsUnique()
                        .HasDatabaseName("ix_verification_codes_user_id_address_address_type");

                    b.ToTable("verification_codes", "address_verifications");
                });

            modelBuilder.Entity("Altinn.Verification.Core.AddressVerifications.Models.VerifiedAddress", b =>
                {
                    b.Property<int>("VerifiedAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("verified_address_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("VerifiedAddressId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("VerifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("VerifiedAddressId")
                        .HasName("pk_verified_addresses");

                    b.HasIndex(new[] { "UserId", "Address", "AddressType" }, "ix_user_id_address_address_type")
                        .IsUnique()
                        .HasDatabaseName("ix_verified_addresses_user_id_address_address_type");

                    b.ToTable("verified_addresses", "address_verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
