namespace Altinn.Verification.Core.AddressVerifications.Models
{
    /// <summary>
    /// Represents a verified address, including information about the user, and address type.
    /// </summary>
    public class VerifiedAddress
    {
        /// <summary>
        /// Gets or sets the user identifier associated with the verified address.
        /// </summary>
        public int UserId { get; set; }

        /// <summary>
        /// Gets or sets the id for the verification. Generated by the database.
        /// </summary>
        public int VerifiedAddressId { get; set; }

        private string _address = string.Empty;

        /// <summary>
        /// Gets or sets the address (e.g., email or phone number) associated with the verified address.
        /// Setter always trims and converts the value to lower case.
        /// </summary>
        public string Address
        {
            get => _address;
            set => _address = VerificationCode.FormatAddress(value);
        }

        /// <summary>
        /// Gets or sets the type of address (e.g., Email or Sms) associated with the verified address.
        /// </summary>
        public AddressType AddressType { get; set; }

        /// <summary>
        /// Gets or sets the date and time when the address was verified.
        /// </summary>
        public DateTime VerifiedAt { get; set; }

        /// <summary>
        /// Gets or sets the verification type for the address.
        /// </summary>
        public VerificationType VerificationType { get; set; } = VerificationType.Verified;
    }
}
