namespace Altinn.Verification.Core.AddressVerifications.Models
{
    /// <summary>
    /// Represents a verification code used for address verification, including information about the user, code, expiration, and address type.
    /// </summary>
    public class VerificationCode
    {
        /// <summary>
        /// Gets or sets the user identifier associated with the verification code.
        /// </summary>
        public int UserId { get; init; }

        /// <summary>
        /// Gets or sets the unique identifier for the verification code. Generated by the database.
        /// </summary>
        public int VerificationCodeId { get; init; }

        /// <summary>
        /// Gets the number of failed attempts to use the verification code.
        /// </summary>
        public int FailedAttempts { get; private set; } = 0;

        /// <summary>
        /// Gets or sets the expiration date and time of the verification code.
        /// </summary>
        public DateTime Expires { get; init; }

        /// <summary>
        /// Gets or sets the creation date and time of the verification code.
        /// </summary>
        public DateTime Created { get; init; }

        /// <summary>
        /// Gets or sets the hash of the verification code.
        /// </summary>
        public string VerificationCodeHash { get; init; } = string.Empty;

        private string _address = string.Empty;

        /// <summary>
        /// Gets or sets the address (e.g., email or phone number) associated with the verification code.
        /// Setter always trims and converts the value to lower case.
        /// </summary>
        public string Address
        {
            get => _address;
            set => _address = FormatAddress(value);
        }

        /// <summary>
        /// Gets or sets the type of address (e.g., Email or Sms) associated with the verification code.
        /// </summary>
        public AddressType AddressType { get; init; }

        /// <summary>
        /// Format the address by trimming whitespace and converting to lower case. This ensures consistency in how addresses are stored and compared.
        /// </summary>
        /// <param name="address">The address to format</param>
        /// <returns>Returns the formatted address</returns>
        public static string FormatAddress(string address)
        {
            return (address ?? string.Empty).Trim().ToLowerInvariant();
        }

        /// <summary>
        /// Increments the count of failed attempts to use the verification code. This can be used to track how many times a user has attempted to verify with this code.
        /// </summary>
        public void IncrementFailedAttempts()
        {
            FailedAttempts++;
        }
    }
}
